name: FE dev deployment

on:
  push:
    branches: ['fe-prod']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: 'employees-app'
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: pwd
      - name: Install dependencies
        run: dir

      - name: Create build
        run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./build s3://employees-app

      - name: Create invalidation
        run: aws cloudfront create-invalidation --distribution-id E15X1CDF0EE9NW --paths "/*"
